### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by valsha** [Xon/XenForo2-RedisCache#4]
plugin version 2.1.3

`[Fri Feb 13 18:50:19.125946 2018] [:error] [pid 22306] [client xxxxxx:24037] PHP Fatal error:  Uncaught Error: Class 'SV\\RedisCache\\Redis' not found in /var/www/html/forum.forum.biz/public_html/src/XF/CacheFactory.php:56\nStack trace:\n#0 /var/www/html/forum.forum.biz/public_html/src/XF/CacheFactory.php(24): XF\\CacheFactory->instantiate('SV\\\\RedisCache\\\\R...', Array)\n#1 /var/www/html/forum.forum.biz/public_html/src/XF/App.php(472): XF\\CacheFactory->create('SV\\\\RedisCache\\\\R...', Array)\n#2 /var/www/html/forum.forum.biz/public_html/src/XF/Container.php(28): XF\\App->XF\\{closure}(Object(XF\\Container))\n#3 /var/www/html/forum.forum.biz/public_html/src/XF/App.php(494): XF\\Container->offsetGet('cache')\n#4 /var/www/html/forum.forum.biz/public_html/src/XF/Container.php(28): XF\\App->XF\\{closure}(Object(XF\\Container))\n#5 /var/www/html/forum.forum.biz/public_html/src/XF/App.php(1393): XF\\Container->offsetGet('registry')\n#6 /var/www/html/forum.forum.biz/public_html/src/XF/Container.php(28): XF\\App->XF\\{closure}(Object(XF\\Container))\n#7 /var/www/html/forum.forum.biz/public_html/src/XF/App.php(1213): X in /var/www/html/forum.forum.biz/public_html/src/XF/CacheFactory.php on line 56, referer: https://forum.forum.biz/forums/hi.11/`

**Comment by Xon** [comment]
Make sure the files are uploaded, and have the correct file permissions.

Beyond that, I'm only able to offer support on the official XenForo forums.
