### ISSUE TITLE
Library change

### ISSUE THREAD

**Issue by kickdev** [Xon/XenForo2-RedisCache#8]
The supplement is very good and behaves very well. But why not use more advanced features?
https://github.com/nrk/predis
Much more extensive features and if you need exactly asynchronous then there is also the opportunity to use the library from the same author:
Much more extensive features and if you need exactly asynchronous then it is also possible to use the library from the same author built on ReactPhp. I really like reactphp lately and use it on my own. Cool thing
https://github.com/nrk/predis-async
In general, in addition to this, there are a bunch of third-party libraries for reactphp.
https://github.com/clue/reactphp-redis
https://github.com/WyriHaximus/reactphp-cache-redis
But as for me, the library from Zend Framework has outlived itself a long time ago like this framework. But in general, I would consider replacing with predis. Per place using this library.
Yes, maybe it would be better to have something like that out of the box, but as we know the XenForo developers are very lazy.

**Comment by Xon** [comment]
Changing the redis library this add-on uses is massive change, and I've got other add-ons which depend on the interface. The additional features that predis offer really isn't required in an XenForo application, and adding async behavior is non-trivial (that is it is really complex).

Also XenForo 2 uses doctrine-cache, not Zend Framework.
